### ISSUE TITLE
Interrupt not triggering on pin PIN_PC0 with ATmega644 and MightyCore

### ISSUE THREAD

**Issue by remiserriere** [matafonoff/J1850-VPW-Arduino-Transceiver-Library#13]
Hello, 

I can't get the RX pin interrupt to trigger on my setup. I'm pretty sure of the pin number, and I have used it as a SoftwareSerial input pin before moving to your code. 
I tried to change _currState to public so I could monitor the pin change, and it stays at 0. 

My guess is that the PCInterrupts are not handled the same way with this setup... 
I added a basic reset function called at the beginning of the PCint function in interrupts.cpp, and it's not being called at all.
Can you please help?

Thank you in advance!

**Comment by matafonoff** [comment]
The code is working fine for Arduino based on atmega328. If you are using other controller, you should try add support for it
