### ISSUE TITLE
Compatibility with IDE 2.0.3

### ISSUE THREAD

**Issue by TaylorRL95** [matafonoff/J1850-VPW-Arduino-Transceiver-Library#17]
Hello Stephan,

I'm trying to use this library with v2.0.3 and I am seeing quite a few errors with some of the library functions. It worked successfully last year in April while I read information from my Harley Davidson motorcycle.
Here are the errors I see, when compiling my own code or the J1850_to_serial example included in the library download:

~/Arduino/libraries/J1850-VPW-Arduino-Transceiver-Library/src/j1850vpw.cpp: In member function 'uint8_t J1850VPW::send(uint8_t*, uint8_t, int16_t)':
~Arduino/libraries/J1850-VPW-Arduino-Transceiver-Library/src/j1850vpw.cpp:348:52: warning: invalid conversion from 'uint8_t {aka unsigned char}' to 'J1850_ERRORS' [-fpermissive]
     return handleErrorsInternal(J1850_Write, result);
                                                    ^
~Arduino/libraries/J1850-VPW-Arduino-Transceiver-Library/src/j1850vpw.cpp:74:14: note:   initializing argument 2 of 'J1850_ERRORS J1850VPW::handleErrorsInternal(J1850_Operations, J1850_ERRORS)'
 J1850_ERRORS J1850VPW::handleErrorsInternal(J1850_Operations op, J1850_ERRORS err)
              ^~~~~~~~
~Arduino/libraries/J1850-VPW-Arduino-Transceiver-Library/src/interrupts.cpp: In function 'void PCint(uint8_t)':
~Arduino/libraries/J1850-VPW-Arduino-Transceiver-Library/src/interrupts.cpp:161:56: warning: invalid conversion from 'volatile void*' to 'void*' [-fpermissive]
                 PCintFunc[pin](currValue, PCintData[pin]);
                                           ~~~~~~~~~~~~~^
~Arduino/libraries/J1850-VPW-Arduino-Transceiver-Library/src/pins.cpp: In constructor 'Pin::Pin()':
~Arduino/libraries/J1850-VPW-Arduino-Transceiver-Library/src/pins.cpp:169:19: warning: invalid conversion from 'int' to 'PIN_MODES' [-fpermissive]
     this->_mode = 0;


I tried to go in and edit the library to fix these issues, however I'm not familiar enough with programming to understand what is going on in most of these functions. If you have a chance to fix it that would be great.

Thanks,
Taylor

**Comment by matafonoff** [comment]
Hello! You could create a pull request with fixes for new IDE. Unfortunately I don't have  hardware for testing at the moment.
