### ISSUE TITLE
What does the J1850_ERR_ARBITRATION_LOST error mean? 

### ISSUE THREAD

**Issue by ataveras64** [matafonoff/J1850-VPW-Arduino-Transceiver-Library#18]
I keep getting the  J1850_ERR_ARBITRATION_LOST error, what exactly does that mean and how do I fix it? The error appears continuously on my serial monitor like every second.

**Comment by flyboy013** [comment]
It means you are attempting to send a message at the same instance as another node and you lost out on arbitration.  A sender monitors what's on wire, and for instance, when its send a low signal and it sees a high signal on the wire, it knows that someone else is sending and you have lost and should retry sending later.  It sounds odd that you are getting so many of these.  Are there alot of nodes?  Is it possible that the pin you are sending is miswired and is high all the time?
