### ISSUE TITLE
Round trip?

### ISSUE THREAD

**Issue by Devon7** [matafonoff/J1850-VPW-Arduino-Transceiver-Library#3]
Has this library been able to establish two-way communication with an OBD2 VPW bus?

J1850VPW::send fails with WRITE J1850_ERR_ARBITRATION_LOST
as passive Tx invariably sees active Rx, even when not connected
so it's only seeing its own output with no possible interference.
Perhaps my implementation of your circuit is slow to change?

I'd delay 8 µs before collision checking
given that SAE J1850 says to filter glitches < 8 µs
according to j1850_wp.pdf _Implementing the J1850 Protocol_ by D. John Oliver of Intel.

**Comment by matafonoff** [comment]
Interrupts must be switched off during transmission, so no loop back could
occur.

вс, 11 окт. 2020 г., 00:40 Devon Sean McCullough <notifications@github.com>:

**Comment by Devon7** [comment]
Ok, failure to communicate, no clue what
you're talking about and vice versa.  Hazard
of staying up way too late.  Will follow up
in the morning when I can write coherently.

Hardware Carrier Sense Multiple Access (CSMA)
is an essential feature of J1850 VPW, we never
call it "loop back" which is a different concept.
Yes, interrupts are disabled but that's software,
we're talking capacitance, impedance, etc. here.

```
if (nbits & 1) // always start with passive symbol
{
    unsigned long microseconds;
    delay = (temp_byte & 0x80) ? TX_LONG : TX_SHORT; // send correct pulse length
    __txPin.write(PASSIVE);                          // set bus passive
    now = micros();
    while ((microseconds = micros() - now) < delay)
    {
        if (8 <= microseconds && // 8 µs glitch delay before collision checking
            __rxPin.read() == ACTIVE)
        {
            result = J1850_ERR_ARBITRATION_LOST;
            goto stop;
        }
    }
}
```

**Comment by Devon7** [comment]
Test program measures 10±2 µs delay between Tx rising edge and consequent Rx
when not connected; 1 ms delay from Tx falling edge to low Rx in a car,
which could be a real collision after the BRK/SOF sent by the test,
happens every time, who knows, no scope
so making a fancier test program.

**Comment by matafonoff** [comment]
What car are you trying to communicate with?

пн, 12 окт. 2020 г., 03:29 Devon Sean McCullough <notifications@github.com>:

**Comment by Devon7** [comment]
1995 Toyota Tercel 4 door sedan made in Japan, VPW pins on OBD connector.
Not all 1995 cars had OBD2 but this has a certification sticker under the hood.
Does this look plausible to you?
```
/* B10011001 = 0x99 = first guess at a generic simple header, palindromic as endianness unclear
	100	Medium Priority (000 = highest)
	1	Single Byte Header
	1	IFR Not Allowed
	0	Functional Addressing
	0	no extended address
	1	no data in this message */
const PROGMEM uint8_t menu[][5] = {{'P', 3, 0x99, 0x01, 0x00}, // PID 01-20 support
				   {'Q', 3, 0x99, 0x01, 0x20}, // PID 21-40 support
				   {'S', 3, 0x99, 0x01, 0x1C}, // OBD standards this vehicle conforms to
				   {'V', 3, 0x99, 0x09, 0x02}, // Vehicle Identification Number (VIN)
				   {'O', 3, 0x99, 0x01, 0x1D}, // Oxygen sensors present
				   {'M', 3, 0x99, 0x01, 0x01}, // Monitor status since DTCs cleared
				   {'T', 3, 0x99, 0x01, 0x05}, // Engine Coolant Temperature (ECT)
				   {'R', 3, 0x99, 0x01, 0x1F}  // Run time since engine start
};
```

**Comment by matafonoff** [comment]
Sorry for answering late. Had no time for this project.

I was implementing subset of J1850VPW that is enough and applicable for Chrsyler vehicles. Not all features are supported.
