### ISSUE TITLE
Received Messages with IFR are silently lost at CRC check stage

### ISSUE THREAD

**Issue by fredmcc** [matafonoff/J1850-VPW-Arduino-Transceiver-Library#8]
@matafonoff  Firstly thank you so much for developing this library. It has been extremely helpful for me.
I was having a lot of difficulty understanding what was going on when there were messages on the vehicle bus I was seeing with other tools but not with this library and an Arduino.
I traced it back to when an IFR frame is present the receive logic doesn't handle it and it goes through with the extra byte and fails CRC and gets silently dropped.

I submitted a pull request that detects the IFR in the frame, flags an error, but still returns the main part of the frame which usually is all that is needed. The other tools I have used seem to present the non IFR part of the frame also in this situation.

**Comment by matafonoff** [comment]
Hi! Glad to here that it helps you!

Some vehicles use there own implementation of j1850 protocol with no respect to standard spec. For instance chrysler/dodge does not respect flags in headers. There are messages that must have IFR and 3 bytes of header, but they are just 3 bytes length messages (1 byte header, 1 byte of data, crc). 
Moreover, there are messages that supposed to have IFR and 3 bytes of data but they have message length that varies from 3 to 10 bytes (including header byte and crc) and all tools I was working with respects this protocol modification. 

I was thinking about implementing strict protocol implementation (with parsing header flags to get message params), but I have no vehicle to test with.

**Comment by matafonoff** [comment]
And one more thing: for chrysler/dodge vehicles first byte looks like to be an id of the message, not a header as described in spec.

**Comment by fredmcc** [comment]
Yes. I am working on a Jeep which would be the same I think. From what I can work out 1st byte is an id. I don't think the flags like IFR and header length really mean anything in the header.
So the way you have implemented it is good I think. You can deal with that stuff at a higher level.
There were 2 messages that have an IFR that weren't appearing at all. One message is 0xB0 which controls the engine check lamp which I need. With the changes I made that message is now reported without the IFR. But I think the IFR is just a single byte acknowledgement from another module anyway.

**Comment by matafonoff** [comment]
I'm just curious if chrysler/dodge and jeep has some messages in common.

What does message 0x10 stands for? 
What does message 0xf0 stands for?

Chrysler uses first message for rpm/map data. Second one is for vin

**Comment by fredmcc** [comment]
0x10
Bytes 1,2 RPM x 4
Bytes 3,4 Vehicle Speed x 128 kph
Byte 5 Manifold Absolute pressure kpa

0xf0 
VIN - Vehicle identification number. 17 ascii characters over 5 frames
First byte is first character location.

**Comment by fredmcc** [comment]
They are the same company so I assume its all quite common

**Comment by matafonoff** [comment]
Have you decoded many of them? I've got some of messages decoded but there
is a lot of work still pending.

**Comment by fredmcc** [comment]
Have you looked at SAE-J2178? You can find it online fairly easily.
It is the SAE recommended practice for headers etc and lays out a lot of what you are looking for. From what I have seen Chrysler/Jeep follows a lot of the recommended messages. There are also a lot of manufacturer specific messages which I dont have much insight into as the recommended ones cover most of what I need.

**Comment by matafonoff** [comment]
Haven't seen this before! Thanks a lot!
